version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      -  ./www:/var/www
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:443"
    links:
      - php-fpm
    working_dir: /var/www
  
  php-fpm:
    build:
      context: ./
      dockerfile: ./docker/php-fpm.docker
    volumes:
      - ./www:/var/www
      - ./docker/php/default.ini:/usr/local/etc/php/conf.d/default.ini
    depends_on:
      - mysql
    working_dir: /var/www

  mysql:
    image: mysql:8
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=app
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=app
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "33061:3306"

  adminer:
    image: michalhosna/adminer
    ports:
      - "8081:8080"
    environment:
      ADMINER_DB: app
      ADMINER_PASSWORD: secret
      ADMINER_SERVER: mysql
      ADMINER_USERNAME: app
      ADMINER_AUTOLOGIN: 1